source "https://rubygems.org"

ruby "3.2.3"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 2.8"
gem "dotenv-rails", "~> 2.8"
gem "rack-cors", "~> 2.0"

group :development, :test do
  gem "rspec-rails", "~> 6.1"
end
